version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:

  build-and-test:
    executor: python/default
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Linting
          command: flake8

  build-docker-image:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build
          command: docker build -t oc_lettings_docker_build .

  push-image-dockerhub:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: docker login -u $DH_username -p $DH_password
      - run:
          name: Link to DockerHub
          command: docker tag oc_lettings_docker_build:latest $DH_username/oc_lettings_docker_build:latest
      - run:
          name: push Docker image
          command: docker push $DH_username/oc_lettings_docker_build:latest

workflows:
  test_linting_build_deploy:
    jobs:
      - build-and-test
      - build-docker-image:
          requires:
            - build-and-test
      - push-image-dockerhub:
          context: OCP13_context
          requires:
            - build-docker-image